//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public int AdId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime PostDate { get; set; }
        public int Price { get; set; }
        public Nullable<int> ProfitAmount { get; set; }
        public int UserId { get; set; }
        public int CityId { get; set; }
        public int CategoryId { get; set; }
        public int AdTypeId { get; set; }
        public int AdStatusId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual AdStatuses AdStatuses { get; set; }
        public virtual AdTypes AdTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
